### ISSUE TITLE
Velocity

### ISSUE THREAD

**Issue by Techirion** [Samsuik/Sakura#12]
Not sure if this is working as expected but with default config we had many players reporting that velocity is waaay off, i.e. they could make others fly just by spam hitting them (i've disabled hit delay and that's all that was changed related to pvp), maybe it would make sense to add option to disable velocity (keep it 1.20.4 default)?

**Comment by Samsuik** [comment]
Should be fixed with 2f29a1a01b1ec617ae7d59d41ee1781d8ac55147. I had implemented the `require-ground` option wrong, so players and entities could receive vertical knockback while still in the air.

Let me know if there's still knockback issues with Sakura, I fixed all the issues I noticed looking at the entity knockback patch.
